# Generated by Django 3.1.1 on 2020-09-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=255)),
                ('Founder', models.CharField(max_length=255)),
                ('Contect_Information', models.CharField(max_length=255)),
                ('Description', models.TextField()),
            ],
        ),
    ]
