# Generated by Django 3.1.1 on 2020-09-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostandFound', '0002_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
