# Generated by Django 3.1.1 on 2020-09-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostandFound', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(blank=True, default='http://placehold.it/750x500', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
